django_memo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memo/', include('memo.urls')),
    path('memo/<int>', include('memo.urls')),
]

memo/urls.py
from django.urls import path

from memo import views

app_name = 'memo'
urlpatterns = [
    path('<int:node_id>', views.browse_node),
    path('', views.browse),
]

memo/models.py
from django.db import models


class Node(models.Model):
    title = models.CharField(null=False, max_length=100)
    text = models.CharField(max_length=1000)
    date = models.DateTimeField('updated at')

memo/forms.py
from django import forms


class Node(forms.Form):
    title = forms.CharField(
        label='タイトル',
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'w100',
        }),
    )
    text = forms.CharField(
        label='本文',
        max_length=1000,
        widget=forms.Textarea(attrs={
            'class': 'w100',
        }),
    )

memo/views.py
from com.yoclabo.routing import Router


def browse(request):
    r = Router.MemoRouter()
    r.request = request
    return r.run()


def browse_node(request, node_id):
    r = Router.MemoRouter()
    r.request = request
    r.parameters['node_id'] = node_id
    return r.run()

templates/memo/layout/list.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        <!--
        .bg_fill {
            width: 100%;
            text-align: center;
        }

        .width_constraint {
            display: inline-block;
            width: 85%;
        }

        .line {
            display: inline-block;
            width: 100%;
            line-height: 50px;
            text-align: left;
        }

        .left {
            display: inline-block;
            width: 20%;
            float: left;
        }

        .auto {
            display: inline-block;
            width: auto;
        }

        -->
    </style>
</head>
<body>
<div class="bg_fill">
    <span class="width_constraint">
        {% block list %}{% endblock %}
    </span>
    <hr>
    <span class="width_constraint">
        {% block post %}{% endblock %}
    </span>
</div>
</body>
</html>

templates/memo/layout/node.html
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        <!--
        .bg_fill {
            width: 100%;
            text-align: center;
        }

        .width_constraint {
            display: inline-block;
            width: 85%;
        }

        .line {
            display: inline-block;
            width: 100%;
            line-height: 50px;
            text-align: left;
        }

        -->
    </style>
</head>
<body>
<div class="bg_fill">
    <span class="width_constraint">
        {% block node %}{% endblock %}
    </span>
</div>
</body>
</html>

templates/memo/page/list.html
{% extends 'memo/layout/list.html' %}

{% block title %}List{% endblock %}

{% block list %}
    {% for n in nodes %}
        <form method="post" action="">
            {% csrf_token %}
            <span class="line">
                <input type="hidden" name="id" value="{{ n.id }}">
                <span class="left">{{ n.date }}</span>
                <span class="auto">
                    <a href="/memo/{{ n.id }}">{{ n.title }}</a>
                    <input type="submit" value="削除">
                </span>
            </span>
        </form>
    {% endfor %}
{% endblock %}

{% block post %}
    <form method="post" action="">
        {% csrf_token %}
        <span class="line">
            <span class="left"><label for="id_title">{{ form.title.label }}</label></span>
            <span class="auto">{{ form.title }}</span>
        </span>
        <span class="line">
            <span class="left"><label for="id_text">{{ form.text.label }}</label></span>
            <span class="auto">{{ form.text }}</span>
        </span>
        <input type="submit">
    </form>
{% endblock %}

templates/memo/page/node.html
{% extends 'memo/layout/node.html' %}

{% block title %}{{ title }}{% endblock %}

{% block node %}
    <a href="/memo/">List</a>
    <span class="line">{{ title }}</span>
    <hr>
    <span class="line">{{ text|linebreaksbr }}</span>
    <hr>
    <span class="line">{{ date }}</span>
{% endblock %}